server:
  port: 9003
spring:
  datasource:
    driver-class-name: org.h2.Driver
    initialize: false
    name: foodboxdb
    password: password
    url: jdbc:h2:file:./foodboxdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: admin
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ce2516bfb0a9bcbb3faa
            clientSecret: 62647c404c428df12126a2a8aba6023f07bbe41e
# ...  
